### PR TITLE
Create multiple mscorlib repro in IL instead of cs

### PR DESCRIPTION
**Pull request by twsouthwick**
This repro is complicated in CS and requires a build machine with VS 2013 to build correctly. Encoding the multiple mscorlib in IL simplifies this greatly.

### CODE REVIEW

**Comment by mjrousos** [comment]
LGTM

**Comment by twsouthwick** [comment]
@mjrousos I added a ps1 script to rebuild all the IL so those not sure how to use ilasm can see how to do it for the repros. Is it true that ilasm is not deterministic? I can't find that documented, but it always produces different results, so I added that as a note in there.

**Comment by twsouthwick** [comment]
@mmitche We're seeing build failures on OSX CI builds - is this a known issue (both active PRs are hitting this on this repo)

**Comment by mmitche** [comment]
@twsouthwick Yeah.  the lab where the OSX machines is located has some failing hardware that needs replacement.  There is no ETA on a fix at the moment.

**Comment by twsouthwick** [comment]
thanks @mmitche . We'll ignore them for now, then

**Comment by mjrousos** [comment]
Also, @twsouthwick, regarding the different the non-deterministic ilasm output, this is expected. [PE files include a 4-byte timestamp in their header](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680547(v=vs.85).aspx#coff_file_header__object_and_image_) indicating when the file was created. Whenever we re-create the assemblies, that will be different. The rest of the file should be unchanged.

**Pull request merged**
