### PR TITLE
Adding Cryptography, Activator, Type.Name recommended changes

### LINKED ISSUE #180: VS Extension 1.1.10808.0: Information on Type usage
When I analyze my C# Portable Client Library in VC 2015, I get error icon on targets .NET Framework 4.6.1, Mono 3.3.0.0, Xamarin.Android 4.12.1 and Xamarin.iOS 7.2.2:

System.Type          

get_Name

I think some recommended changes needs to be added here. 
I couldn't really find anything about this issue at first, but from https://github.com/Microsoft/dotnet-apiport/issues/113 and https://dotnetcademy.net/Learn/4/Pages/3 I recon I need to change to TypeInfo.

Keep up the good work!

Kind Regards,
Keld Ølykke

### PR DESCRIPTION
**Pull request by conniey**
Fixes #180 along with adding more recommendations

### CODE REVIEW

**Comment by twsouthwick** [comment]
LGTM

**Comment by twsouthwick** [comment]
LGTM

@weshaggard do these recommendations for the crypto stuff look good?

**Comment by weshaggard** [comment]
LGTM

@bartonjs for the crypto recommended changes.

**Comment by bartonjs** [comment]
LGTM

**Pull request merged**
