### PR TITLE
Remove ApiPort.VisualStudio.2015

### PR DESCRIPTION
**Pull request by chlowell**
This removes our Visual Studio 2015 extension.

### CODE REVIEW

**Comment by chlowell** [comment]
Sorry to report it doesn't. Resolving the binding conflicts by upgrading to newer dependencies introduces ~40 warnings from VS SDK analyzers, which I haven't worked through.

**Comment by conniey** [comment]
> Sorry to report it doesn't. Resolving the binding conflicts by upgrading to newer dependencies introduces ~40 warnings from VS SDK analyzers, which I haven't worked through.

Maybe we shouldn't upgrade them. Ahaha.

**Comment by chlowell** [comment]
I'm thinking the same thing but haven't determined exactly which dependencies we need. We can hold off merging this until that's done, this work isn't really complete if we ship assemblies we don't use.

**Comment by chlowell** [comment]
I used a newer version of the VS threading library which does not include the analyzers 🙈 and eliminates the binding warnings. Two birds, one hug.

**Pull request merged**
