### PR TITLE
Fix test results location for CI build.

### PR DESCRIPTION
**Pull request by conniey**
Trx logger does not output test results to the same location that windows builds do.

### CODE REVIEW

**Comment by conniey** [comment]
@mmitche Hey Matt, I was wondering if you could help me with what I am missing? I am trying to get some Linux builds for CI.. and I added them here, it appears as though only the windows builds are running.

https://github.com/Microsoft/dotnet-apiport/blob/master/netci.groovy

**Comment by mmitche** [comment]
@conniey These changes will need to be committed before they will take effect.  We can check that the CI file is okay with @dotnet-bot test ci please

**Comment by conniey** [comment]
@mmitche Thanks for the response! I had committed those changes in a previous merged PR #433 and wanted to use this improvement to the committed code to see if it worked.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@conniey Appears the generator hadn't rerun and so the new runs hadn't propagated from your previous change.  Fixed.

**Comment by conniey** [comment]
@dotnet-bot test ci please

**Comment by conniey** [comment]
@dotnet-bot test this please

**Pull request merged**
