### PR TITLE
Add setup for portability offline

### PR DESCRIPTION
**Pull request by JJVertical**

### CODE REVIEW

**Comment by conniey** [comment]
LGTM.

**Comment by twsouthwick** [comment]
The project won't open now if someone doesn't have wix installed. Can this be in a separate solution?

**Comment by twsouthwick** [comment]
@JJVertical Did you still want to get this in?

**Comment by mmitche** [comment]
@dotnet-bot test this please (ci test)

**Comment by twsouthwick** [comment]
@dotnet-bot test this please (ci test)

**Comment by mmitche** [comment]
FYI it looks like you'll need to resolve the conflicts first (since your pre-conflict commit has no build.ps1)

**Comment by mmitche** [comment]
@dotnet-bot test this please (random check, ignore)

**Comment by twsouthwick** [comment]
I'm going to close this for now. Please reopen if you want to fix the merge issues.

**Pull request closed without merging**
