### PR TITLE
Remove TODO items in the breaking change markdown files.

### PR DESCRIPTION
**Pull request by JJVertical**

### CODE REVIEW

**Comment by mjrousos** [comment]
LGTM

**Comment by twsouthwick** [comment]
Why did you remove some of the md files?

**Comment by mjrousos** [comment]
Those were both breaking changes that came from customer reports (not MSDN) that we weren't able to repro (remember when someone - Charles? Connie?) was trying to write analyzers and hit a couple issues in a row that didn't seem to repro? @JJVertical has opened a couple internal issues against me to track closing on whether or not there's anything worth actually tracking in an md file for these.

**Comment by twsouthwick** [comment]
Good to know

**Comment by twsouthwick** [comment]
Fixes #130

**Pull request merged**
