### PR TITLE
Remove Microsoft.AspNetCore.App version

### PR DESCRIPTION
**Pull request by jeremymeng**
The version is inferred based on the SDK installed. The ASP.NET Core 2.1 project
templates doesn't include version for it either.

### CODE REVIEW

**Comment by jeremymeng** [comment]
There are build errors in building some of the test projects due to assembly resolution conflicts - some of the packages are still depending on aspnetcore1.0.

**Comment by khellang** [comment]
You might want to hold off on this; https://github.com/aspnet/Home/issues/3292

**Comment by jeremymeng** [comment]
Thanks @khellang for the info!

**Comment by jeremymeng** [comment]
Abandoning now and will visit later.

**Pull request closed without merging**
