### PR TITLE
Update a couple recommended changes

### PR DESCRIPTION
**Pull request by twsouthwick**
Now that @conniey got recommended changes coming from the repo, we can more easily update them.

### CODE REVIEW

**Comment by twsouthwick** [comment]
@weshaggard Does the Framework Description recommended change apply to any other types?

**Comment by weshaggard** [comment]
@Priya91 can you work with @twsouthwick get the recommeded changes updated for the RuntimeInformation API's you added.

**Comment by Priya91** [comment]
@weshaggard Sure i'll follow up!

**Comment by Priya91** [comment]
@twsouthwick 
- Use RuntimeInformation.ProcessArchitecture in place of System.Environment.Is64BitProcess
- Use RuntimeInformation.OSArchitecture in place of System.Environment.Is64BitOperatingSystem

```FrameworkDescription``` and ```OSDescription``` in ```RuntimeInformation``` are not replacements for ```Environment.Version``` or ```Environment.OSVersion```, since these API can be used for making runtime decisions whereas the RuntimeInformation description APIs are only for logging and display purposes.

**Comment by weshaggard** [comment]
@Priya91 they don't have to be direct replacements but if we can point people to the new APIs that will help them satisfy some of their scenarios that is what we are after here in the recommended changes.

**Comment by twsouthwick** [comment]
@Priya91 Keeping in mind that these are not 1:1 mappings as @weshaggard described, does this look right?

**Comment by Priya91** [comment]
@twsouthwick Yes, LGTM!

**Pull request merged**
