### PR TITLE
Update third party notices

### PR DESCRIPTION
**Pull request by jeremymeng**

### CODE REVIEW

**Comment by twsouthwick** [comment]
@dotnet-bot retest please

**Comment by twsouthwick** [comment]
@dotnet-bot test this please

**Comment by conniey** [comment]
As part of this, could you move `/src/ApiPort.VisualStudio/Resources/API Portability Analyzer Alpha Pre-Release License Terms.rtf` to `/docs/LicenseTerms/` and then update `ApiPort.VisualStudio.csproj` to link to it? It'll help to keep all our license stuff in the same place.

Example
```xml
    <Content Include="..\..\..\docs\LicenseTerms\API Portability Analyzer Alpha Pre-Release License Terms.rtf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
```

**Comment by jeremymeng** [comment]
Good idea. Will do.

**Comment by conniey** [comment]
@mmitche Hey Matt, The Ubuntu and OSX builds are failing.. but we can't see the details. is there something wrong with https://ci2.dot.net/?

**Comment by mmitche** [comment]
@conniey The ci and ci2 instances are down for a region move, which should be completed this afternoon.  There was an outage notification.  Did you get it?

**Comment by conniey** [comment]
@mmitche Ahh! I just saw that email resent. Thanks. :)

**Pull request merged**
