### PR TITLE
Service Fabric Manifests and API Port updates to require endpoint is specified in env var

### PR DESCRIPTION
**Pull request by mjrousos**
Adds some container deployment-related resources for backend services:

- Dockerfiles and Docker-compose files
- Service Fabric manifests

Also, updates ApiPort to require the PortabilityService endpoint be explicitly set (for now) either through an env. var or a command line switch (-e).

### CODE REVIEW

**Comment by mjrousos** [comment]
I can see that. Where would you prefer the manifests to live? In a ServiceFabric folder in root? Perhaps in Deploy/ServiceFabric?

**Comment by chlowell** [comment]
Something like `deploy/ServiceFabric` sounds good to me.

**Comment by mjrousos** [comment]
Ah, I just realized that ApiPort tests are busted by my change to require -e. Investigating...

**Comment by mjrousos** [comment]
Tests are now fixed.

**Comment by twsouthwick** [comment]
LGTM Are you ready to merge in?

**Comment by twsouthwick** [comment]
in case you were wondering, I was opening/closing as the CI wasn't building the PR - was hoping to trigger it.

**Pull request merged**
