### PR TITLE
Update project files to all use PackageReferences

### PR DESCRIPTION
**Pull request by twsouthwick**

### CODE REVIEW

**Comment by twsouthwick** [comment]
I don't have VS2015 - can you verify when you have a chance? (my VS is acting up anyway with the latest windows flight/VS flight)

**Comment by conniey** [comment]
@twsouthwick I pulled this branch, ran `.\build.ps1 -Configuration Debug -Platform AnyCPU -CreateNugetPackages` and I don't see the ApiPort.vsix in `bin\Debug\ApiPort.Vsix` anymore. Also repros on Release builds.

**Comment by twsouthwick** [comment]
hmmm - I'll take a look.

**Comment by twsouthwick** [comment]
Seems to not be working with the vsix. I'll close it for now - it may be fixed with 15.3 which had some big updates.

**Pull request closed without merging**
