### PR TITLE
Add doc for Unicode v8.0 support breaking change

### PR DESCRIPTION
**Pull request by jeremymeng**
@twsouthwick @mjrousos @conniey

### CODE REVIEW

**Comment by mjrousos** [comment]
LGTM. Let's be sure to fill in the 'more info' link once we have something to point it at. @HollyAM, fyi

**Comment by HollyAM** [comment]
LGTM. Should we link to 4.6.2 change list until we get the MSDN API docs updated? https://github.com/Microsoft/dotnet/blob/master/releases/net462/dotnet462-changes.md

**Comment by mjrousos** [comment]
Yea, that's a good idea. At least the link will go somewhere, even if there's not a lot more info than on this page.

**Comment by jeremymeng** [comment]
Thanks! I will add that link and submit PR against our internal repo.

**Pull request closed without merging**
