### PR TITLE
Importing recommended changes from catalog

### PR DESCRIPTION
**Pull request by conniey**
This imports the existing recommended changes to be consumed by PortabilityService

@twsouthwick, @terrajobst

### CODE REVIEW

**Comment by twsouthwick** [comment]
Awesome! It feels like having a folder hierarchy all the way to the member/property is a lot. What about having it at the containing namespace level? ie recommended changes for all things in System.Net would be in System/Net/[recommended changes]. This would reduce some of the duplication of recommended changes.

**Comment by conniey** [comment]
@twsouthwick That makes sense! I just updated the PR with changes belonging to the same namespace... Does this look better. :)

**Comment by twsouthwick** [comment]
Much better! LGTM

**Comment by twsouthwick** [comment]
btw - why no spaces in the file names?

**Comment by conniey** [comment]
I had manually created names for them that way. I fixed them to include spaces. :)

**Pull request merged**
